---
# Location to store Cloudware logs
general:
  log_file: '/var/log/cloudware.log'

# Provider credentials
provider:
  azure:
    tenant_id: '%TENANT_ID%'
    subscription_id: '%SUBSCRIPTION_ID%'
    client_secret: '%CLIENT_SECRET%'
    client_id: '%CLIENT_ID%'

  aws:
    access_key_id: '%ACCESS_KEY%'
    secret_access_key: '%SECRET_KEY%'
