---
general:
  # Location to store Cloudware logs
  log_file: '/var/log/cloudware.log'

provider:
  # Azure provider configuration
  azure:
    tenant_id: '%TENANT_ID%'
    subscription_id: '%SUBSCRIPTION_ID%'
    client_secret: '%CLIENT_SECRET%'
    client_id: '%CLIENT_ID%'

  aws:
    # AWS provider configuration
    access_key_id: '%ACCESS_KEY%'
    secret_access_key: '%SECRET_KEY%'
