---
# Location to store Cloudware logs
general:
  log_file: '/var/log/cloudware.log'

# Azure provider configuration
provider:
  azure:
    tenant_id: '%TENANT_ID%'
    subscription_id: '%SUBSCRIPTION_ID%'
    client_secret: '%CLIENT_SECRET%'
    client_id: '%CLIENT_ID%'

  aws:
    # AWS provider configuration
    access_key_id: '%ACCESS_KEY%'
    secret_access_key: '%SECRET_KEY%'

# Optional machine type overrides
machine_types:
  azure:
    compute:
      tiny: 'Standard_DS1_v2'
      small: ''
      medium: ''
      large: ''
      xlarge: ''
    generic:
      tiny: 'Standard_DS1_v2'
      small: ''
      medium: ''
      large: ''
      xlarge: ''
    memory:
      tiny: 'Standard_DS1_v2'
      small: ''
      medium: ''
      large: ''
      xlarge: ''
    gpu:
      tiny: 'Standard_DS1_v2'
      small: ''
      medium: ''
      large: ''
      xlarge: ''

  aws:
    compute:
      tiny:
