
language: ruby
dist: trusty
rvm:
 - 2.4.1
sudo: required
install:
  - cp ./etc/config.yml.example ./etc/config.yml
  - sed -i 's#/var/log#/tmp#g' ./etc/config.yml
  - touch /tmp/flightconnector.log
  - bundle install
script:
  - export CLOUDWARE_PROVIDER=aws
  - rspec
