---
Description: 'Flight Domain Template'
Mappings:
  RegionMap:
    eu-west-1:
      "AMI": "ami-d266dfab"
    eu-west-2:
      "AMI": "ami-c5f11ea2"
Resources:

  gateway1network1Interface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SourceDestCheck: false
      GroupSet:
        - %securitygroup%
      PrivateIpAddress: 10.10.2.101
      SubnetId: %network1SubnetID% 
      Tags:
        -
          Key: 'Name'
          Value: 'gateway1'
        -
          Key: 'alcescluster'
          Value: gateway1

  gateway1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      ImageId: !FindInMap ["RegionMap", !Ref "AWS::Region", "AMI"]
      InstanceType: t2.small
      Monitoring: true
      KeyName: %keyname%
      NetworkInterfaces:
        -
          NetworkInterfaceId: !Ref gateway1network1Interface
          DeviceIndex: 0
        -
          NetworkInterfaceId: !Ref gateway1network2Interface
          DeviceIndex: 1

      Tags:
        -
          Key: 'Name'
          Value: 'gateway1'
        -
          Key: 'alcescluster'
          Value: gateway1
      UserData:
        Fn::Base64:
          Fn::Join:
            - ''
            - - "#cloud-config\n"
              - "hostname: gateway1\n"
              - "fqdn: gateway1.pri.mycluster.cluster.local\n"

  gateway1publicIp:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  gateway1publicIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      NetworkInterfaceId: !Ref gateway1network1Interface
      AllocationId: !GetAtt gateway1publicIp.AllocationId

Outputs:
  gateway1TAGID:
    Description: gateway1TAGID
    Value: !Ref gateway1
  gateway1TAGIP:
    Description: gateway1TAGIP
    Value: !Ref gateway1publicIp
