---
Description: 'Cloudware machine [slave] template'
Parameters:
  cloudwareId:
    Type: String
    Description: 'Enter the Cloudware UUID'

  cloudwareDomain:
    Type: String
    Description: 'Enter the Cloudware domain name'

  networkId:
    Type: String
    Description: 'Enter the VPC/network ID'

  prvSubnetId:
    Type: String
    Description: 'Enter the prv subnet ID'

  mgtSubnetId:
    Type: String
    Description: 'Enter the mgt subnet ID'

  prvIp:
    Type: String
    Description: 'Enter the prv subnet IP'

  mgtIp:
    Type: String
    Description: 'Enter the mgt subnet IP'

  prvSubnetCidr:
    Type: String
    Description: 'Enter the prv subnet CIDR'

  mgtSubnetCidr:
    Type: String
    Description: 'Enter the mgt subnet CIDR'

  keyPairName:
    Default: 'cloudware'
    Type: String
    Description: 'Select the AWS keypair to assign to the instance'

  vmType:
    Type: String
    Description: 'Enter the size of the instance'

  vmRole:
    Type: String
    Description: 'Enter the Cloudware instance type'

  vmName:
    Type: String
    Description: 'Enter the desired instance name'

Mappings:
  RegionMap:
    eu-west-1:
      "AMI": "ami-0d063c6b"

Resources:
  securityGroupSlave:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['-', [!Ref cloudwareDomain, !Ref vmName]]
      GroupDescription: 'Cloudware seucirty group for slave machine'
      VpcId: !Ref networkId
      SecurityGroupIngress:
        -
          IpProtocol: 'icmp'
          FromPort: '8'
          ToPort: '-1'
          CidrIp: '0.0.0.0/0'
          Description: 'Allow ping'
      SecurityGroupEgress:
        -
          IpProtocol: '-1'
          FromPort: 0
          ToPort: 65535
          CidrIp: '0.0.0.0/0'
          Description: 'Allow outbound internet access'
      Tags:
        -
          Key: 'Name'
          Value: !Join ['-', [!Ref cloudwareDomain, !Ref vmName]]
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain

  securityGroupPrv:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['-', [!Ref cloudwareDomain, !Ref vmName, 'prv']]
      GroupDescription: 'Cloudware security group for slave machine prv interface'
      VpcId: !Ref networkId
      SecurityGroupIngress:
        -
          IpProtocol: '-1'
          CidrIp: !Ref prvSubnetCidr
          Description: 'Allow unrestricted access from the prv subnet'
      Tags:
        -
          Key: 'Name'
          Value: !Join ['-', [!Ref cloudwareDomain, !Ref vmName, 'prv']]
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain

  securityGroupMgt:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['-', [!Ref cloudwareDomain, !Ref vmName, 'mgt']]
      GroupDescription: 'Cloudware security group for slave machine mgt interface'
      VpcId: !Ref networkId
      SecurityGroupIngress:
        -
          IpProtocol: '-1'
          CidrIp: !Ref mgtSubnetCidr
          Description: 'Allow unrestricted access from the mgt subnet'
      Tags:
        -
          Key: 'Name'
          Value: !Join ['-', [!Ref cloudwareDomain, !Ref vmName, 'mgt']]
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain

  prvInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: !Join [' ', [!Ref cloudwareDomain, !Ref vmName, 'prv network interface']]
      GroupSet:
        - !Ref securityGroupPrv
        - !Ref securityGroupSlave
      PrivateIpAddress: !Ref prvIp
      SubnetId: !Ref prvSubnetId
      Tags:
        -
          Key: 'Name'
          Value: !Join ['-', [!Ref cloudwareDomain, !Ref vmName, 'prv']]
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain

  mgtInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: !Join [' ', [!Ref cloudwareDomain, !Ref vmName, 'mgt network interface']]
      GroupSet:
        - !Ref securityGroupMgt
      PrivateIpAddress: !Ref mgtIp
      SubnetId: !Ref mgtSubnetId
      Tags:
        -
          Key: 'Name'
          Value: !Join ['-', [!Ref cloudwareDomain, !Ref vmName, 'mgt']]
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain

  Slave:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      ImageId: !FindInMap ["RegionMap", !Ref "AWS::Region", "AMI"]
      InstanceType: !Ref vmType
      Monitoring: true
      KeyName: !Ref keyPairName
      NetworkInterfaces:
        -
          NetworkInterfaceId: !Ref prvInterface
          DeviceIndex: 0
        -
          NetworkInterfaceId: !Ref mgtInterface
          DeviceIndex: 1
      Tags:
        -
          Key: 'Name'
          Value: !Join ['-', [!Ref cloudwareDomain, !Ref vmName]]
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain
        -
          Key: 'cloudware_machine_role'
          Value: !Ref vmRole
        -
          Key: 'cloudware_machine_name'
          Value: !Ref vmName
        -
          Key: 'cloudware_prv_subnet_ip'
          Value: !Ref prvIp
        -
          Key: 'cloudware_mgt_subnet_ip'
          Value: !Ref mgtIp
