
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: db
  username: postgres

development:
  <<: *default
  database: cloudware

test:
  <<: *default
  database: cloudware-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
