---
Description: 'Flight Domain Template'
Resources:
  myclusterNetwork:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        -
          Key: 'Name'
          Value: '%deployment_name%'
        -
          Key: 'flightcluster'
          Value: %deployment_name%

  myclusterInternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: myclusterNetwork
    Properties:
      Tags:
        -
          Key: 'Name'
          Value: '%deployment_name%'
        -
          Key: 'flightcluster'
          Value: %deployment_name%
  
  myclusterInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref myclusterInternetGateway
      VpcId: !Ref myclusterNetwork

  myclusterRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: myclusterInternetGatewayAttachment
    Properties:
      VpcId: !Ref myclusterNetwork
      Tags:
        -
          Key: 'Name'
          Value: '%deployment_name%'
        -
          Key: 'flightcluster'
          Value: %deployment_name%

  myclusternetwork1Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.10.0.0/19
      VpcId: !Ref myclusterNetwork
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      Tags:
        -
          Key: 'Name'
          Value: '%deployment_name%'
        -
          Key: 'flightcluster'
          Value: %deployment_name%

  network1SubnetRouteTableAssocation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref myclusternetwork1Subnet
      RouteTableId: !Ref myclusterRouteTable

  myclusterRouteInternetGateway:
    Type: AWS::EC2::Route
    DependsOn: myclusterInternetGatewayAttachment
    Properties:
      RouteTableId: !Ref myclusterRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref myclusterInternetGateway
  
  myclusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: mycluster
      GroupDescription: 'Primary SG for %deployment_name%'
      VpcId: !Ref myclusterNetwork
      SecurityGroupIngress:
        -
          IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
          Description: 'Allow inbound SSH access'
        -
          IpProtocol: 'icmp'
          FromPort: '8'
          ToPort: '-1'
          CidrIp: '0.0.0.0/0'
          Description: 'Allow ping'
      SecurityGroupEgress:
        -
          IpProtocol: '-1'
          FromPort: 0
          ToPort: 65535
          CidrIp: '0.0.0.0/0'
          Description: 'Allow outbound internet access'
      Tags:
        -
          Key: 'Name'
          Value: '%deployment_name%'
        -
          Key: 'flightcluster'
          Value: %deployment_name%

Outputs:
  networkID:
    Description: networkID
    Value: !Ref myclusterNetwork
  securitygroup:
    Description: securitygroup
    Value: !Ref myclusterSecurityGroup
  network1SubnetID:
    Description: network1subnetID
    Value: !Ref myclusternetwork1Subnet
