---
Description: 'Cloudware machine [master] template'
Parameters:
  cloudwareId:
    Type: String
    Description: 'Enter the Cloudware UUID'
  
  cloudwareDomain:
    Type: String
    Description: 'Enter the Cloudware domain name'

  networkId:
    Type: String
    Description: 'Enter the VPC/network ID'

  prvSubnetId:
    Type: String
    Description: 'Enter the prv subnet ID'

  mgtSubnetId:
    Type: String
    Description: 'Enter the mgt subnet ID'

  prvSubnetIp:
    Type: String
    Description: 'Enter the prv subnet IP'

  mgtSubnetIp:
    Type: String
    Description: 'Enter the mgt subnet IP'

  prvSubnetCidr:
    Type: String
    Description: 'Enter the prv subnet CIDR'

  mgtSubnetCidr:
    Type: String
    Description: 'Enter the mgt subnet CIDR'

  keyPairName:
    Default: 'cloudware'
    Type: String
    Description: 'Select the AWS keypair to assign to the instance'

  vmSize:
    Type: String
    Description: 'Enter the size of the instance'

  vmType:
    Type: String
    Description: 'Enter the Cloudware instance type'

Mappings:
  RegionMap:
    eu-west-1:
      "AMI": "ami-37c2f643"

Resources:
  securityGroupPrv:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['-', [!Ref cloudwareDomain, 'sg']]
      GroupDescription: 'Cloudware security group for master machine prv interface'
      VpcId: !Ref networkId
      SecurityGroupIngress:
        -
          IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
          Description: 'Allow inbound SSH access'
        - 
          IpProtocol: '-1'
          CidrIp: !Ref prvSubnetCidr
          Description: 'Allow unrestricted access from the prv subnet'
      Tags:
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain

  securityGroupMgt:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['-', [!Ref cloudwareDomain, 'sg']]
      GroupDescription: 'Cloudware security group for master machine mgt interface'
      VpcId: !Ref networkId
      SecurityGroupIngress:
        -
          IpProtocol: '-1'
          CidrIp: !Ref mgtSubnetCidr
          Description: 'Allow unrestricted access from the mgt subnet'
      Tags:
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain

  prvInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: !Join [' ', [!Ref cloudwareDomain, !Ref vmName, 'prv network interface']]
      GroupSet:
        - securityGroupPrv
      PrivateIpAddress: !Ref prvSubnetIp
      SubnetId: !Ref prvSubnetId
      Tags:
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain

  mgtInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: !Join [' ', [!Ref cloudwareDomain, !Ref vmName, 'mgt network interface']]
      GroupSet:
        - securityGroupMgt
      PrivateIpAddress: !Ref mgtSubnetIp
      SubnetId: !Ref mgtSubnetId
      Tags:
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain

  master:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      ImageId: !FindInMap ["RegionMap", !Ref "AWS::Region", "AMI"]
      InstanceType: !Ref vmSize
      Monitoring: true
      KeyName: !Ref keyPairName
      Tags:
        -
          Key: 'cloudware_id'
          Value: !Ref cloudwareId
        -
          Key: 'cloudware_domain'
          Value: !Ref cloudwareDomain
        -
          Key: 'cloudware_machine_type'
          Value: !Ref vmType
        -
          Key: 'cloudware_machine_name'
          Value: !Ref vmName

  prvInterfaceAttachment:
    Type: AWS::EC2::NetworkInterfaceAttachment
    DependsOn:
      - prvInterface
      - master
    Properties:
      DeleteOnTermination: true
      DeviceIndex: 0
      InstanceId: !Ref master
      NetworkInterfaceId: !Ref prvInterface

  mgtInterfaceAttachment:
    Type: AWS::EC2::NetworkInterfaceAttachment
    DependsOn:
      - mgtInterface
      - master
    Properties:
      DeleteOnTermination: true
      DeviceIndex: 0
      InstanceId: !Ref master
      NetworkInterfaceId: !Ref mgtInterface
